name: Update & Build 

on:
  workflow_dispatch:
    inputs:
      build-paperclip:
        description: 'Build a paperclip jar?'
        required: false
        type: boolean

run-name: Update from Paper repo  

concurrency:
  group: update-paper
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:

    name: Update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Fetch upstream repo
        run: git fetch upstream 

      - name: Pull upstream master branch
        run: git pull upstream master

      - name: Push to GitHub
        run: git push
